import type { Metadata } from "next";
import { OWNER, SITE } from "@/lib/legal";

export const metadata: Metadata = { title: "Legal notice · Globe Trip" };

export default function Page() {
  return (
    <>
      <h1>Legal notice</h1>
      <p>
        As required by Spain&apos;s Law 34/2002 on Information Society Services and
        Electronic Commerce (LSSI-CE), these are the details of the owner of this website.
      </p>

      <h2>Owner</h2>
      <dl>
        <dt>Responsible person</dt><dd>{OWNER.name}</dd>
        {OWNER.taxId && (<><dt>Tax ID</dt><dd>{OWNER.taxId}</dd></>)}
        <dt>Contact email</dt><dd>{OWNER.email}</dd>
        <dt>Country</dt><dd>Spain</dd>
        <dt>Website</dt><dd>{SITE.url}</dd>
      </dl>

      <h2>What this site is</h2>
      <p>
        {SITE.name} is a personal project with no direct profit motive. It turns public
        links to travel videos into routes on a globe and suggests trip plans. It is
        provided as is, with no guarantee of availability or continuity.
      </p>

      <h2>Using the service</h2>
      <ul>
        <li>Only paste links to public content. Don&apos;t upload material you don&apos;t have rights to.</li>
        <li>Automated or bulk use, or use that degrades the service for others, is not allowed.</li>
        <li>The service may limit the number of analyses per visitor to protect its costs.</li>
      </ul>

      <h2>Accuracy of the information</h2>
      <p>
        Routes, itineraries, budgets, activities and risk levels are generated by an
        artificial intelligence model from the video&apos;s content. They may contain
        mistakes. <strong>They are not travel, safety or financial advice.</strong> Before
        you travel, check official sources, such as your government&apos;s travel advice.
      </p>

      <h2>Intellectual property</h2>
      <p>
        The code and design of {SITE.name} belong to its owner. The videos analysed
        belong to their creators and to the platforms where they are published: this
        site doesn&apos;t store or redistribute them, it only reads frames temporarily to
        identify places.
      </p>

      <h2>Governing law</h2>
      <p>This notice is governed by Spanish law. The Spanish version is the reference text.</p>
    </>
  );
}
