import type { Metadata } from "next";
import { OWNER, SITE } from "@/lib/legal";

export const metadata: Metadata = { title: "Affiliate links · Globe Trip" };

export default function Page() {
  return (
    <>
      <h1>Affiliate links</h1>
      <p className="legal-lead">
        Current status: <strong>there are no affiliate links active yet</strong> on{" "}
        {SITE.name}. This page explains how they will work when there are.
      </p>

      <h2>What it means</h2>
      <p>
        Some suggested activities and places to stay may link to external booking
        platforms. If you book through one of those links, the platform pays a commission
        to the owner of this website. <strong>It costs you nothing extra</strong>: the
        price is the same as going there yourself.
      </p>

      <h2>How it affects what you see</h2>
      <p>
        Suggestions are generated by the model from the destination, not from money. A
        place doesn&apos;t appear earlier or higher because it pays a commission, and no
        platform pays to appear. If that ever changed, it would be said here and marked on
        the card itself.
      </p>

      <h2>How they are marked</h2>
      <p>
        Every affiliate link will be clearly marked on the card where it appears and will
        carry <code>rel=&quot;sponsored nofollow&quot;</code>, as advertising rules and good
        practice require.
      </p>

      <h2>Cookies</h2>
      <p>
        These links use third-party cookies to attribute the booking, usually for about 30
        days. They won&apos;t be switched on without your prior consent.
      </p>

      <h2>Responsibility</h2>
      <p>
        Booking, payment, cancellations and customer service are handled by the external
        platform, not by {SITE.name}. Any problem with a booking is dealt with directly
        with them.
      </p>

      <h2>Questions</h2>
      <p>Write to {OWNER.email}.</p>
    </>
  );
}
